# Generated by Django 5.0.3 on 2026-08-01 05:35

import pgvector.django
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrowsingSession',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(db_index=True, max_length=255)),
                ('url', models.TextField()),
                ('domain', models.CharField(db_index=True, max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('active_duration_seconds', models.IntegerField(default=0)),
                ('background_audio_seconds', models.IntegerField(default=0)),
                ('engagement_score', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ai_intent', models.CharField(blank=True, max_length=100, null=True)),
                ('user_override_intent', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DomainSemanticCache',
            fields=[
                ('domain_or_url', models.CharField(max_length=512, primary_key=True, serialize=False)),
                ('cached_intent', models.CharField(max_length=100)),
                ('embedding', pgvector.django.VectorField(dimensions=1536, help_text='Vector embedding of the page metadata')),
                ('last_verified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [pgvector.django.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='embedding_hnsw_idx', opclasses=['vector_l2_ops'])],
            },
        ),
    ]
