# Generated by Django 5.0.3 on 2026-08-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='browsingsession',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='browsingsession',
            name='keystrokes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='browsingsession',
            name='scrolls',
            field=models.IntegerField(default=0),
        ),
    ]
